/**
 * foodData.js
 * Central food data store for Ăn Gì?
 * This module is isolated so it can be replaced with an API call in the future.
 *
 * To swap with an API, replace the `foods` array export with an async function
 * that fetches from your endpoint and returns the same object shape.
 */

export const foods = [
  // ─── BREAKFAST ──────────────────────────────────────────────────────────────
  {
    id: 1,
    name: 'Phở Bò',
    meal: 'breakfast',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Tô phở bò truyền thống với nước dùng thanh ngọt, thịt bò mềm và bánh phở dai ngon.',
    ingredients: ['Bánh phở', 'Thịt bò', 'Nước dùng xương', 'Hành lá', 'Ngò gai', 'Giá đỗ'],
    calories: 450,
    price: '50,000đ – 80,000đ',
    image: 'https://picsum.photos/600/900?random=1',
  },
  {
    id: 2,
    name: 'Phở Gà',
    meal: 'breakfast',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Phở gà thơm dịu với nước dùng gà trong vắt, thịt gà xé tơi và rau thơm tươi.',
    ingredients: ['Bánh phở', 'Thịt gà', 'Nước dùng gà', 'Hành lá', 'Ngò rí'],
    calories: 380,
    price: '45,000đ – 70,000đ',
    image: 'https://picsum.photos/600/900?random=2',
  },
  {
    id: 3,
    name: 'Bún Bò Huế',
    meal: 'breakfast',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Bún bò Huế cay nồng đặc trưng xứ Huế với chả cua béo ngậy và thịt bò giò heo.',
    ingredients: ['Bún', 'Thịt bò', 'Chả cua', 'Sả', 'Mắm ruốc', 'Ớt'],
    calories: 520,
    price: '45,000đ – 75,000đ',
    image: 'https://picsum.photos/600/900?random=3',
  },
  {
    id: 4,
    name: 'Bún Riêu',
    meal: 'breakfast',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Bún riêu cua đồng với gạch cua béo ngậy, cà chua chua ngọt và đậu hũ chiên giòn.',
    ingredients: ['Bún', 'Riêu cua', 'Cà chua', 'Đậu hũ chiên', 'Rau sống', 'Mắm tôm'],
    calories: 400,
    price: '35,000đ – 60,000đ',
    image: 'https://picsum.photos/600/900?random=4',
  },
  {
    id: 5,
    name: 'Hủ Tiếu',
    meal: 'breakfast',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Hủ tiếu Nam Bộ với sợi dai trong vắt, nước dùng ngọt thanh và topping đa dạng.',
    ingredients: ['Hủ tiếu', 'Thịt heo', 'Tôm', 'Hành phi', 'Cần tây'],
    calories: 430,
    price: '35,000đ – 65,000đ',
    image: 'https://picsum.photos/600/900?random=5',
  },
  {
    id: 6,
    name: 'Mì Quảng',
    meal: 'breakfast',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Mì Quảng đặc sản miền Trung với sợi mì vàng đậm, nước nhân ít mà đậm đà.',
    ingredients: ['Mì Quảng', 'Thịt heo', 'Tôm', 'Trứng cút', 'Đậu phộng', 'Bánh tráng'],
    calories: 490,
    price: '35,000đ – 60,000đ',
    image: 'https://picsum.photos/600/900?random=6',
  },
  {
    id: 7,
    name: 'Bánh Mì',
    meal: 'breakfast',
    category: 'Ăn nhẹ',
    style: 'Món khô',
    description: 'Bánh mì giòn rụm nhân thịt nguội pate trứng và rau sống tươi mát kiểu Việt Nam.',
    ingredients: ['Bánh mì', 'Pate', 'Thịt nguội', 'Trứng', 'Dưa leo', 'Rau mùi', 'Ớt'],
    calories: 350,
    price: '20,000đ – 40,000đ',
    image: 'https://picsum.photos/600/900?random=7',
  },
  {
    id: 8,
    name: 'Xôi Mặn',
    meal: 'breakfast',
    category: 'Ăn nhẹ',
    style: 'Món khô',
    description: 'Xôi nếp dẻo thơm với topping lạp xưởng trứng muối và hành phi vàng ươm.',
    ingredients: ['Gạo nếp', 'Lạp xưởng', 'Trứng muối', 'Hành phi', 'Nước cốt dừa'],
    calories: 420,
    price: '20,000đ – 45,000đ',
    image: 'https://picsum.photos/600/900?random=8',
  },
  {
    id: 9,
    name: 'Cháo Gà',
    meal: 'breakfast',
    category: 'Ăn nhẹ',
    style: 'Món nước',
    description: 'Cháo gà bổ dưỡng, mềm mịn với thịt gà xé tơi, gừng và hành ngò thơm lừng.',
    ingredients: ['Gạo', 'Thịt gà', 'Gừng', 'Hành lá', 'Ngò rí', 'Tiêu'],
    calories: 290,
    price: '25,000đ – 45,000đ',
    image: 'https://picsum.photos/600/900?random=9',
  },
  {
    id: 10,
    name: 'Cháo Lòng',
    meal: 'breakfast',
    category: 'Ăn nhẹ',
    style: 'Món nước',
    description: 'Cháo lòng heo thơm bùi với lòng non, gan, tiết và quẩy giòn rụm.',
    ingredients: ['Gạo', 'Lòng heo', 'Gan heo', 'Tiết', 'Quẩy', 'Gừng'],
    calories: 340,
    price: '25,000đ – 50,000đ',
    image: 'https://picsum.photos/600/900?random=10',
  },
  {
    id: 11,
    name: 'Bò Kho',
    meal: 'breakfast',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Bò kho sốt vàng thơm ngào ngạt với thịt bò mềm tan kèm bánh mì nóng giòn.',
    ingredients: ['Thịt bò', 'Cà rốt', 'Sả', 'Ngũ vị hương', 'Bánh mì'],
    calories: 480,
    price: '45,000đ – 75,000đ',
    image: 'https://picsum.photos/600/900?random=11',
  },
  {
    id: 12,
    name: 'Bánh Cuốn',
    meal: 'breakfast',
    category: 'Ăn nhẹ',
    style: 'Món khô',
    description: 'Bánh cuốn mỏng mềm nhân thịt mộc nhĩ cuộn tròn, chấm nước mắm pha chua ngọt.',
    ingredients: ['Bột gạo', 'Thịt heo', 'Mộc nhĩ', 'Hành phi', 'Nước mắm'],
    calories: 310,
    price: '25,000đ – 50,000đ',
    image: 'https://picsum.photos/600/900?random=12',
  },
  {
    id: 13,
    name: 'Bánh Canh',
    meal: 'breakfast',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Bánh canh sợi bột dai mềm trong nước dùng đậm đà với chả cá thơm ngon.',
    ingredients: ['Bánh canh bột lọc', 'Chả cá', 'Tôm', 'Hành lá', 'Tiêu'],
    calories: 410,
    price: '35,000đ – 60,000đ',
    image: 'https://picsum.photos/600/900?random=13',
  },
  {
    id: 14,
    name: 'Bún Cá',
    meal: 'breakfast',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Bún cá nước lèo ngọt thanh với miếng cá chiên vàng giòn và rau sống phong phú.',
    ingredients: ['Bún', 'Cá lóc', 'Cà chua', 'Rau muống', 'Thì là', 'Mắm ruốc'],
    calories: 390,
    price: '35,000đ – 60,000đ',
    image: 'https://picsum.photos/600/900?random=14',
  },
  {
    id: 15,
    name: 'Nui',
    meal: 'breakfast',
    category: 'Ăn nhẹ',
    style: 'Món nước',
    description: 'Nui xào hoặc nấu súp kiểu Sài Gòn với heo bằm tôm tươi và sốt cà chua đậm đà.',
    ingredients: ['Nui', 'Thịt heo', 'Tôm', 'Cà chua', 'Hành tây'],
    calories: 360,
    price: '25,000đ – 45,000đ',
    image: 'https://picsum.photos/600/900?random=15',
  },

  // ─── MAIN MEALS ──────────────────────────────────────────────────────────────
  {
    id: 16,
    name: 'Cơm Tấm',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Cơm tấm Sài Gòn đặc trưng với sườn nướng thơm lừng, bì và chả trứng béo ngậy.',
    ingredients: ['Cơm tấm', 'Sườn heo', 'Bì', 'Chả trứng', 'Mỡ hành', 'Dưa leo'],
    calories: 620,
    price: '45,000đ – 80,000đ',
    image: 'https://picsum.photos/600/900?random=16',
  },
  {
    id: 17,
    name: 'Cơm Gà',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Cơm gà Hội An thơm vàng nấu bằng nước luộc gà, kèm thịt gà xé mướt và gừng muối.',
    ingredients: ['Cơm gà', 'Thịt gà', 'Rau răm', 'Gừng', 'Hành phi'],
    calories: 570,
    price: '45,000đ – 80,000đ',
    image: 'https://picsum.photos/600/900?random=17',
  },
  {
    id: 18,
    name: 'Cơm Sườn',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Cơm trắng phủ sườn heo nướng than đỏ hồng, mỡ hành và nước mắm pha chua ngọt.',
    ingredients: ['Cơm trắng', 'Sườn heo nướng', 'Mỡ hành', 'Nước mắm pha'],
    calories: 600,
    price: '40,000đ – 70,000đ',
    image: 'https://picsum.photos/600/900?random=18',
  },
  {
    id: 19,
    name: 'Cơm Chiên',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Cơm chiên dương châu xào trứng, tôm, lạp xưởng và rau củ đầy màu sắc.',
    ingredients: ['Cơm', 'Trứng', 'Tôm', 'Lạp xưởng', 'Cà rốt', 'Đậu Hà Lan'],
    calories: 580,
    price: '35,000đ – 65,000đ',
    image: 'https://picsum.photos/600/900?random=19',
  },
  {
    id: 20,
    name: 'Cơm Rang Dưa Bò',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Cơm rang dưa cải muối với thịt bò xào lửa lớn đậm đà hương vị Bắc bộ.',
    ingredients: ['Cơm', 'Thịt bò', 'Dưa cải muối', 'Trứng', 'Tỏi'],
    calories: 560,
    price: '35,000đ – 65,000đ',
    image: 'https://picsum.photos/600/900?random=20',
  },
  {
    id: 21,
    name: 'Bún Chả',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Bún chả Hà Nội truyền thống với chả viên và chả miếng nướng than, nước chấm ngọt.',
    ingredients: ['Bún', 'Chả heo nướng', 'Nước chấm', 'Rau thơm', 'Dưa góp'],
    calories: 500,
    price: '40,000đ – 70,000đ',
    image: 'https://picsum.photos/600/900?random=21',
  },
  {
    id: 22,
    name: 'Bún Thịt Nướng',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Bún thịt nướng miền Nam với thịt heo nướng thơm, nem chua và đồ chua bày biện đẹp mắt.',
    ingredients: ['Bún', 'Thịt heo nướng', 'Nem chua', 'Đồ chua', 'Rau sống', 'Nước mắm'],
    calories: 520,
    price: '40,000đ – 70,000đ',
    image: 'https://picsum.photos/600/900?random=22',
  },
  {
    id: 23,
    name: 'Bún Đậu Mắm Tôm',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Bún đậu Bắc bộ với đậu hũ chiên giòn, thịt luộc và mắm tôm pha chanh ớt.',
    ingredients: ['Bún', 'Đậu hũ chiên', 'Thịt heo luộc', 'Mắm tôm', 'Rau thơm', 'Chả cốm'],
    calories: 550,
    price: '40,000đ – 70,000đ',
    image: 'https://picsum.photos/600/900?random=23',
  },
  {
    id: 24,
    name: 'Bún Mắm',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Bún mắm miền Tây đậm đà với nước dùng mắm cá sặc thơm nồng, hải sản và rau ghém.',
    ingredients: ['Bún', 'Mắm cá', 'Tôm', 'Mực', 'Thịt heo', 'Rau ghém'],
    calories: 540,
    price: '45,000đ – 80,000đ',
    image: 'https://picsum.photos/600/900?random=24',
  },
  {
    id: 25,
    name: 'Bún Thái',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Bún Thái chua cay ngọt kiểu Thái Lan với hải sản tươi và sả gừng thơm nức.',
    ingredients: ['Bún', 'Tôm', 'Mực', 'Sả', 'Lá chanh', 'Ớt', 'Cà chua'],
    calories: 420,
    price: '50,000đ – 85,000đ',
    image: 'https://picsum.photos/600/900?random=25',
  },
  {
    id: 26,
    name: 'Miến Gà',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Miến gà trong vắt thanh đạm với thịt gà xé và nấm mộc nhĩ rất thích hợp khi nhẹ bụng.',
    ingredients: ['Miến', 'Thịt gà', 'Mộc nhĩ', 'Hành lá', 'Gừng', 'Nước dùng gà'],
    calories: 360,
    price: '35,000đ – 60,000đ',
    image: 'https://picsum.photos/600/900?random=26',
  },
  {
    id: 27,
    name: 'Miến Ngan',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Miến ngan thơm béo với thịt ngan đặc trưng và nước dùng vàng óng thanh ngọt.',
    ingredients: ['Miến', 'Thịt ngan', 'Nước dùng', 'Hành phi', 'Rau thơm'],
    calories: 390,
    price: '40,000đ – 70,000đ',
    image: 'https://picsum.photos/600/900?random=27',
  },
  {
    id: 28,
    name: 'Hủ Tiếu Nam Vang',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Hủ tiếu Nam Vang kiểu Campuchia với nước dùng ngọt đặc biệt và hải sản phong phú.',
    ingredients: ['Hủ tiếu', 'Thịt heo', 'Tôm', 'Mực', 'Gan', 'Cần tây'],
    calories: 450,
    price: '40,000đ – 75,000đ',
    image: 'https://picsum.photos/600/900?random=28',
  },
  {
    id: 29,
    name: 'Mì Xào Bò',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Mì xào giòn hoặc mềm với thịt bò lúc lắc và rau củ xào lửa lớn đầy đặn.',
    ingredients: ['Mì trứng', 'Thịt bò', 'Cải ngọt', 'Hành tây', 'Dầu hào'],
    calories: 580,
    price: '45,000đ – 80,000đ',
    image: 'https://picsum.photos/600/900?random=29',
  },
  {
    id: 30,
    name: 'Mì Xào Hải Sản',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Mì xào hải sản thơm ngon với tôm mực nghêu xào lửa lớn và sốt đặc trưng.',
    ingredients: ['Mì trứng', 'Tôm', 'Mực', 'Nghêu', 'Rau cải', 'Dầu hào'],
    calories: 540,
    price: '55,000đ – 90,000đ',
    image: 'https://picsum.photos/600/900?random=30',
  },
  {
    id: 31,
    name: 'Hủ Tiếu Xào',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Hủ tiếu xào dai ngon với nhân hải sản hoặc thịt heo xào lửa lớn thơm phức.',
    ingredients: ['Hủ tiếu', 'Tôm', 'Thịt heo', 'Hẹ', 'Giá đỗ', 'Trứng'],
    calories: 510,
    price: '40,000đ – 70,000đ',
    image: 'https://picsum.photos/600/900?random=31',
  },
  {
    id: 32,
    name: 'Mì Cay',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Mì cay Hàn Quốc nồng nàn với nhiều cấp độ cay, topping phong phú và phô mai chảy.',
    ingredients: ['Mì', 'Sốt cay Hàn', 'Xúc xích', 'Rau', 'Trứng', 'Phô mai'],
    calories: 610,
    price: '50,000đ – 120,000đ',
    image: 'https://picsum.photos/600/900?random=32',
  },
  {
    id: 33,
    name: 'Lẩu Thái',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Lẩu Thái nước dùng chua cay thơm sả với hải sản tươi và nấm thả lẩu ngập tràn.',
    ingredients: ['Nước lẩu Thái', 'Tôm', 'Mực', 'Nghêu', 'Nấm', 'Cà chua', 'Sả'],
    calories: 450,
    price: '150,000đ – 250,000đ',
    image: 'https://picsum.photos/600/900?random=33',
  },
  {
    id: 34,
    name: 'Lẩu Bò',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Lẩu bò nhúng nước dùng đậm đà với các phần thịt bò tươi ngon và rau xanh thơm.',
    ingredients: ['Nước lẩu bò', 'Thịt bò', 'Bắp bò', 'Gân bò', 'Rau xanh', 'Bún'],
    calories: 600,
    price: '150,000đ – 280,000đ',
    image: 'https://picsum.photos/600/900?random=34',
  },
  {
    id: 35,
    name: 'Lẩu Gà Lá É',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Lẩu gà nấu lá é đặc sản Tây Nguyên thơm lạ miệng và bổ dưỡng.',
    ingredients: ['Gà', 'Lá é', 'Nấm tràm', 'Bún', 'Rau thơm'],
    calories: 480,
    price: '150,000đ – 250,000đ',
    image: 'https://picsum.photos/600/900?random=35',
  },
  {
    id: 36,
    name: 'Lẩu Hải Sản',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Lẩu hải sản nước dùng chua ngọt với tôm hùm nghêu sò và rau tươi xanh mướt.',
    ingredients: ['Nước lẩu', 'Tôm', 'Mực', 'Sò điệp', 'Cua', 'Rau muống'],
    calories: 520,
    price: '180,000đ – 350,000đ',
    image: 'https://picsum.photos/600/900?random=36',
  },
  {
    id: 37,
    name: 'Bò Lúc Lắc',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Bò lúc lắc xào lửa lớn với hành tây cà chua và sốt đặc biệt ăn kèm cơm trắng hoặc bánh mì.',
    ingredients: ['Thịt bò', 'Hành tây', 'Cà chua', 'Tiêu xanh', 'Nước tương'],
    calories: 580,
    price: '70,000đ – 120,000đ',
    image: 'https://picsum.photos/600/900?random=37',
  },
  {
    id: 38,
    name: 'Bò Né',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Bò né chảo gang xèo xèo với thịt bò bít tết trứng pate và bánh mì nóng giòn.',
    ingredients: ['Thịt bò', 'Trứng', 'Pate', 'Bơ', 'Bánh mì', 'Rau ghém'],
    calories: 650,
    price: '60,000đ – 100,000đ',
    image: 'https://picsum.photos/600/900?random=38',
  },
  {
    id: 39,
    name: 'Bò Bít Tết',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Bít tết bò kiểu Pháp Việt với thịt bò mềm thơm sốt tiêu đen và rau củ nướng.',
    ingredients: ['Thịt bò', 'Sốt tiêu', 'Khoai tây chiên', 'Rau xà lách'],
    calories: 700,
    price: '80,000đ – 150,000đ',
    image: 'https://picsum.photos/600/900?random=39',
  },
  {
    id: 40,
    name: 'Gà Nướng',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Gà nướng vàng thơm ướp sả ớt nước mắm đặc biệt ăn kèm muối tiêu chanh ngon miệng.',
    ingredients: ['Gà', 'Sả', 'Ớt', 'Nước mắm', 'Mật ong', 'Muối tiêu chanh'],
    calories: 520,
    price: '60,000đ – 120,000đ',
    image: 'https://picsum.photos/600/900?random=40',
  },
  {
    id: 41,
    name: 'Gà Chiên',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Gà chiên giòn rụm với vỏ ngoài vàng ươm và thịt bên trong mềm mọng nước.',
    ingredients: ['Gà', 'Bột chiên', 'Tỏi', 'Ớt bột', 'Muối'],
    calories: 590,
    price: '55,000đ – 100,000đ',
    image: 'https://picsum.photos/600/900?random=41',
  },
  {
    id: 42,
    name: 'Heo Quay',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Heo quay da giòn tan thơm lừng với thịt mềm ướt và sốt tương hải sản chấm kèm.',
    ingredients: ['Thịt heo', 'Ngũ vị hương', 'Tương đen', 'Dưa muối'],
    calories: 680,
    price: '70,000đ – 130,000đ',
    image: 'https://picsum.photos/600/900?random=42',
  },
  {
    id: 43,
    name: 'Vịt Quay',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Vịt quay Bắc Kinh da giòn mỡ màng thơm lừng ăn kèm bánh tráng và mắm gừng.',
    ingredients: ['Vịt', 'Ngũ vị hương', 'Mật ong', 'Bánh tráng', 'Mắm gừng'],
    calories: 660,
    price: '75,000đ – 140,000đ',
    image: 'https://picsum.photos/600/900?random=43',
  },
  {
    id: 44,
    name: 'Cá Kho Tộ',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Cá kho tộ đậm đà mặn ngọt với nước kho sệt vàng nâu ăn kèm cơm trắng rất đưa cơm.',
    ingredients: ['Cá lóc', 'Nước dừa', 'Nước mắm', 'Đường', 'Tiêu', 'Ớt'],
    calories: 480,
    price: '40,000đ – 75,000đ',
    image: 'https://picsum.photos/600/900?random=44',
  },
  {
    id: 45,
    name: 'Cá Nướng',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Cá nướng lá chuối thơm lừng với hành mỡ và mắm nêm pha chua ngọt trứ danh.',
    ingredients: ['Cá', 'Sả', 'Nghệ', 'Mắm nêm', 'Hành phi'],
    calories: 420,
    price: '50,000đ – 100,000đ',
    image: 'https://picsum.photos/600/900?random=45',
  },
  {
    id: 46,
    name: 'Canh Chua',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Canh chua cá lóc miền Tây với me chua cà chua dứa và các loại rau thơm đặc trưng.',
    ingredients: ['Cá lóc', 'Me', 'Cà chua', 'Dứa', 'Bạc hà', 'Đậu bắp', 'Cần tây'],
    calories: 320,
    price: '40,000đ – 70,000đ',
    image: 'https://picsum.photos/600/900?random=46',
  },
  {
    id: 47,
    name: 'Thịt Kho Trứng',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Thịt kho trứng Tết truyền thống với thịt ba rọi và trứng kho nước dừa thơm béo.',
    ingredients: ['Thịt ba rọi', 'Trứng vịt', 'Nước dừa', 'Nước mắm', 'Đường'],
    calories: 620,
    price: '45,000đ – 80,000đ',
    image: 'https://picsum.photos/600/900?random=47',
  },
  {
    id: 48,
    name: 'Sườn Nướng',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Sườn heo nướng BBQ thơm lừng với sốt đặc biệt và ăn kèm cơm hoặc bánh mì.',
    ingredients: ['Sườn heo', 'Sốt BBQ', 'Mật ong', 'Nước mắm'],
    calories: 650,
    price: '60,000đ – 120,000đ',
    image: 'https://picsum.photos/600/900?random=48',
  },
  {
    id: 49,
    name: 'BBQ',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'BBQ nướng than hồng với thịt hải sản đa dạng, chấm muối tiêu chanh và sốt đặc biệt.',
    ingredients: ['Thịt bò', 'Thịt heo', 'Tôm', 'Mực', 'Rau cuốn', 'Sốt BBQ'],
    calories: 700,
    price: '150,000đ – 350,000đ',
    image: 'https://picsum.photos/600/900?random=49',
  },
  {
    id: 50,
    name: 'Sushi',
    meal: 'main',
    category: 'Ăn nhẹ',
    style: 'Món khô',
    description: 'Sushi Nhật Bản với cơm giấm ướp hải sản tươi và wasabi gừng muối đặc trưng.',
    ingredients: ['Cơm sushi', 'Cá hồi', 'Cá ngừ', 'Rong biển', 'Wasabi', 'Gừng muối'],
    calories: 340,
    price: '80,000đ – 200,000đ',
    image: 'https://picsum.photos/600/900?random=50',
  },
  {
    id: 51,
    name: 'Sashimi',
    meal: 'main',
    category: 'Ăn nhẹ',
    style: 'Món khô',
    description: 'Sashimi hải sản tươi ngon thái lát mỏng đẹp mắt ăn kèm nước tương wasabi Nhật Bản.',
    ingredients: ['Cá hồi tươi', 'Cá ngừ', 'Bạch tuộc', 'Wasabi', 'Nước tương Nhật'],
    calories: 250,
    price: '100,000đ – 250,000đ',
    image: 'https://picsum.photos/600/900?random=51',
  },
  {
    id: 52,
    name: 'Ramen',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Ramen Nhật Bản cổ điển với nước dùng đậm đà, trứng lòng đào và thịt char siu thơm ngon.',
    ingredients: ['Mì ramen', 'Nước dùng tonkotsu', 'Thịt char siu', 'Trứng lòng đào', 'Bamboo', 'Rong biển'],
    calories: 610,
    price: '75,000đ – 150,000đ',
    image: 'https://picsum.photos/600/900?random=52',
  },
  {
    id: 53,
    name: 'Udon',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Udon Nhật với sợi mì trắng dày dai ngon trong nước dùng dashi thanh thoát và topping đa dạng.',
    ingredients: ['Mì udon', 'Nước dashi', 'Tôm tempura', 'Hành lá', 'Kamaboko'],
    calories: 480,
    price: '65,000đ – 130,000đ',
    image: 'https://picsum.photos/600/900?random=53',
  },
  {
    id: 54,
    name: 'Katsu',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Katsu Nhật Bản với thịt heo hoặc gà chiên xù giòn tan ăn kèm cơm và sốt Tonkatsu.',
    ingredients: ['Thịt heo', 'Breadcrumbs', 'Trứng', 'Bắp cải', 'Cơm', 'Sốt Tonkatsu'],
    calories: 640,
    price: '70,000đ – 130,000đ',
    image: 'https://picsum.photos/600/900?random=54',
  },
  {
    id: 55,
    name: 'Curry Rice',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món nước',
    description: 'Cà ri cơm Nhật Bản thơm ngọt vàng óng với thịt khoai tây cà rốt mềm ngon.',
    ingredients: ['Cơm', 'Viên cà ri Nhật', 'Thịt bò', 'Khoai tây', 'Cà rốt', 'Hành tây'],
    calories: 580,
    price: '65,000đ – 120,000đ',
    image: 'https://picsum.photos/600/900?random=55',
  },
  {
    id: 56,
    name: 'Bibimbap',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Bibimbap Hàn Quốc cơm trộn đa sắc màu với rau củ thịt bò và trứng sốt gochujang cay ngọt.',
    ingredients: ['Cơm', 'Thịt bò', 'Rau bina', 'Cà rốt', 'Trứng', 'Sốt gochujang'],
    calories: 520,
    price: '65,000đ – 110,000đ',
    image: 'https://picsum.photos/600/900?random=56',
  },
  {
    id: 57,
    name: 'Tokbokki',
    meal: 'main',
    category: 'Ăn nhẹ',
    style: 'Món nước',
    description: 'Tokbokki bánh gạo Hàn Quốc dai ngon trong sốt gochujang cay ngọt đặc trưng.',
    ingredients: ['Bánh gạo', 'Sốt gochujang', 'Chả cá', 'Hành lá', 'Mè'],
    calories: 380,
    price: '40,000đ – 80,000đ',
    image: 'https://picsum.photos/600/900?random=57',
  },
  {
    id: 58,
    name: 'Kimbap',
    meal: 'main',
    category: 'Ăn nhẹ',
    style: 'Món khô',
    description: 'Kimbap Hàn Quốc cuộn cơm rong biển với nhân rau củ và thịt đầy màu sắc hấp dẫn.',
    ingredients: ['Cơm', 'Rong biển', 'Trứng', 'Cà rốt', 'Cải xanh', 'Thịt bò xào'],
    calories: 320,
    price: '35,000đ – 65,000đ',
    image: 'https://picsum.photos/600/900?random=58',
  },
  {
    id: 59,
    name: 'Pizza',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Pizza Ý đế mỏng giòn hoặc đế dày với phô mai mozzarella kéo sợi và topping phong phú.',
    ingredients: ['Đế pizza', 'Sốt cà chua', 'Phô mai mozzarella', 'Pepperoni', 'Rau'],
    calories: 680,
    price: '80,000đ – 200,000đ',
    image: 'https://picsum.photos/600/900?random=59',
  },
  {
    id: 60,
    name: 'Burger',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Burger bò thịt nướng juicy với phô mai rau tươi sốt đặc biệt kẹp bánh mì mềm thơm.',
    ingredients: ['Bánh bun', 'Patty bò', 'Phô mai', 'Xà lách', 'Cà chua', 'Sốt burger'],
    calories: 720,
    price: '60,000đ – 150,000đ',
    image: 'https://picsum.photos/600/900?random=60',
  },
  {
    id: 61,
    name: 'Pasta',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Pasta Ý nấu al dente với sốt bolognese hoặc carbonara kem béo ngậy và parmesan bào.',
    ingredients: ['Pasta', 'Sốt bolognese', 'Parmesan', 'Basil', 'Tỏi'],
    calories: 620,
    price: '70,000đ – 150,000đ',
    image: 'https://picsum.photos/600/900?random=61',
  },
  {
    id: 62,
    name: 'Steak',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Steak bò Mỹ medium-rare với bơ thảo mộc khoai tây nghiền và rau salad tươi mát.',
    ingredients: ['Bò ribeye', 'Bơ thảo mộc', 'Khoai tây', 'Hành tây', 'Salad'],
    calories: 800,
    price: '150,000đ – 400,000đ',
    image: 'https://picsum.photos/600/900?random=62',
  },

  // ─── SNACKS ──────────────────────────────────────────────────────────────────
  {
    id: 63,
    name: 'Bánh Tráng Trộn',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món khô',
    description: 'Bánh tráng trộn vỉa hè Sài Gòn với tắc muối ớt xoài xanh và các loại sốt thơm ngon.',
    ingredients: ['Bánh tráng', 'Xoài xanh', 'Tắc', 'Muối ớt', 'Tôm khô', 'Trứng cút'],
    calories: 280,
    price: '10,000đ – 25,000đ',
    image: 'https://picsum.photos/600/900?random=63',
  },
  {
    id: 64,
    name: 'Bánh Tráng Nướng',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món khô',
    description: 'Bánh tráng nướng Đà Lạt với trứng mỡ hành xúc xích và sốt tương giòn tan hấp dẫn.',
    ingredients: ['Bánh tráng', 'Trứng', 'Mỡ hành', 'Xúc xích', 'Tương ớt'],
    calories: 300,
    price: '15,000đ – 35,000đ',
    image: 'https://picsum.photos/600/900?random=64',
  },
  {
    id: 65,
    name: 'Cá Viên Chiên',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món khô',
    description: 'Cá viên chiên giòn vàng xiên que chấm tương ớt tương chua ngọt vỉa hè ngon miệng.',
    ingredients: ['Cá viên', 'Bột chiên', 'Tương ớt', 'Tương ngọt'],
    calories: 220,
    price: '5,000đ – 20,000đ',
    image: 'https://picsum.photos/600/900?random=65',
  },
  {
    id: 66,
    name: 'Bò Viên Chiên',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món khô',
    description: 'Bò viên chiên giòn dai ngon xiên que ăn kèm tương đen và tương ớt đặc trưng.',
    ingredients: ['Bò viên', 'Bột chiên', 'Tương đen', 'Tương ớt'],
    calories: 250,
    price: '5,000đ – 20,000đ',
    image: 'https://picsum.photos/600/900?random=66',
  },
  {
    id: 67,
    name: 'Khoai Tây Chiên',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món khô',
    description: 'Khoai tây chiên giòn vàng ươm rắc muối và các loại gia vị đặc biệt ăn không thể ngừng.',
    ingredients: ['Khoai tây', 'Dầu chiên', 'Muối', 'Ớt bột', 'Phô mai'],
    calories: 340,
    price: '20,000đ – 45,000đ',
    image: 'https://picsum.photos/600/900?random=67',
  },
  {
    id: 68,
    name: 'Khoai Lang Lắc',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món khô',
    description: 'Khoai lang lắc bơ muối tiêu thơm phức ngọt bùi là món ăn vặt đang rất hot.',
    ingredients: ['Khoai lang', 'Bơ', 'Muối', 'Tiêu', 'Đường'],
    calories: 290,
    price: '20,000đ – 40,000đ',
    image: 'https://picsum.photos/600/900?random=68',
  },
  {
    id: 69,
    name: 'Takoyaki',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món khô',
    description: 'Takoyaki bánh bạch tuộc Nhật Bản tròn xoe giòn ngoài mềm trong với cá bào và sốt mayonnaise.',
    ingredients: ['Bột Takoyaki', 'Bạch tuộc', 'Cá bào', 'Sốt Takoyaki', 'Mayonnaise'],
    calories: 310,
    price: '30,000đ – 60,000đ',
    image: 'https://picsum.photos/600/900?random=69',
  },
  {
    id: 70,
    name: 'Gà Rán',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món khô',
    description: 'Gà rán giòn rụm thơm gia vị theo kiểu KFC với da ngoài giòn tan và thịt trong mềm ngọt.',
    ingredients: ['Gà', 'Bột chiên xù', 'Gia vị', 'Tỏi', 'Tiêu'],
    calories: 420,
    price: '25,000đ – 60,000đ',
    image: 'https://picsum.photos/600/900?random=70',
  },
  {
    id: 71,
    name: 'Xiên Que',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món khô',
    description: 'Xiên que hỗn hợp với viên bò tôm cá thịt nướng than thơm lừng chấm sốt đặc biệt.',
    ingredients: ['Viên các loại', 'Sốt cay', 'Tương ớt'],
    calories: 260,
    price: '5,000đ – 30,000đ',
    image: 'https://picsum.photos/600/900?random=71',
  },
  {
    id: 72,
    name: 'Bắp Xào',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món khô',
    description: 'Bắp xào bơ tôm khô hành lá thơm béo ngọt là món ăn vặt yêu thích của giới trẻ.',
    ingredients: ['Bắp hạt', 'Bơ', 'Tôm khô', 'Hành lá', 'Muối'],
    calories: 240,
    price: '15,000đ – 30,000đ',
    image: 'https://picsum.photos/600/900?random=72',
  },
  {
    id: 73,
    name: 'Bắp Nướng',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món khô',
    description: 'Bắp nướng than hồng phết bơ mỡ hành thơm ngọt tự nhiên là món vặt kinh điển.',
    ingredients: ['Bắp ngọt', 'Bơ', 'Mỡ hành', 'Muối'],
    calories: 200,
    price: '10,000đ – 25,000đ',
    image: 'https://picsum.photos/600/900?random=73',
  },
  {
    id: 74,
    name: 'Nem Chua Rán',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món khô',
    description: 'Nem chua rán giòn tan bên ngoài chua cay đặc trưng bên trong ăn kèm tương ớt ngon tuyệt.',
    ingredients: ['Nem chua', 'Dầu chiên', 'Tương ớt', 'Tỏi'],
    calories: 270,
    price: '10,000đ – 25,000đ',
    image: 'https://picsum.photos/600/900?random=74',
  },
  {
    id: 75,
    name: 'Chả Giò',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món khô',
    description: 'Chả giò chiên vàng giòn rụm với nhân thịt mộc nhĩ cà rốt ăn kèm rau sống và nước mắm.',
    ingredients: ['Bánh tráng', 'Thịt heo', 'Mộc nhĩ', 'Cà rốt', 'Miến', 'Trứng'],
    calories: 320,
    price: '20,000đ – 45,000đ',
    image: 'https://picsum.photos/600/900?random=75',
  },
  {
    id: 76,
    name: 'Gỏi Cuốn',
    meal: 'snack',
    category: 'Ăn nhẹ',
    style: 'Món khô',
    description: 'Gỏi cuốn tươi mát với tôm thịt bún rau thơm cuộn bánh tráng chấm tương đặc biệt.',
    ingredients: ['Bánh tráng', 'Tôm', 'Thịt heo', 'Bún', 'Xà lách', 'Rau thơm'],
    calories: 180,
    price: '15,000đ – 35,000đ',
    image: 'https://picsum.photos/600/900?random=76',
  },
  {
    id: 77,
    name: 'Kem',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món khô',
    description: 'Kem mát lạnh với nhiều hương vị từ vani socola matcha dâu tây và các vị trái cây.',
    ingredients: ['Sữa', 'Kem tươi', 'Đường', 'Trứng', 'Hương vị'],
    calories: 230,
    price: '20,000đ – 60,000đ',
    image: 'https://picsum.photos/600/900?random=77',
  },
  {
    id: 78,
    name: 'Flan',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món khô',
    description: 'Bánh flan caramel mềm mịn tan trong miệng với sốt caramel đắng ngọt quyến rũ.',
    ingredients: ['Trứng', 'Sữa', 'Đường caramel', 'Vani'],
    calories: 210,
    price: '15,000đ – 35,000đ',
    image: 'https://picsum.photos/600/900?random=78',
  },
  {
    id: 79,
    name: 'Yaourt',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món khô',
    description: 'Yaourt sữa chua tự làm hoặc Vinamilk mát lạnh chua nhẹ và bổ dưỡng cho mọi lứa tuổi.',
    ingredients: ['Sữa tươi', 'Men yogurt', 'Đường', 'Hương vị trái cây'],
    calories: 140,
    price: '10,000đ – 25,000đ',
    image: 'https://picsum.photos/600/900?random=79',
  },
  {
    id: 80,
    name: 'Chè',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món nước',
    description: 'Chè Việt Nam đa dạng từ chè đậu xanh đậu đỏ trôi nước cho đến chè bưởi thạch đặc biệt.',
    ingredients: ['Đậu xanh', 'Nước cốt dừa', 'Đường', 'Thạch', 'Trân châu'],
    calories: 260,
    price: '15,000đ – 40,000đ',
    image: 'https://picsum.photos/600/900?random=80',
  },
  {
    id: 81,
    name: 'Trái Cây Tô',
    meal: 'snack',
    category: 'Ăn vặt',
    style: 'Món khô',
    description: 'Tô trái cây nhiệt đới tươi ngon cắt sẵn với muối ớt tắc và mứt đặc biệt.',
    ingredients: ['Xoài', 'Dưa hấu', 'Dứa', 'Thanh long', 'Muối ớt', 'Tắc'],
    calories: 170,
    price: '20,000đ – 45,000đ',
    image: 'https://picsum.photos/600/900?random=81',
  },

  // ─── DRINKS ──────────────────────────────────────────────────────────────────
  {
    id: 82,
    name: 'Trà Sữa',
    meal: 'drink',
    category: 'Đồ uống',
    style: 'Món nước',
    description: 'Trà sữa thơm béo với trân châu đen dai ngon và trà oolong đặc trưng không thể cưỡng lại.',
    ingredients: ['Trà oolong', 'Sữa tươi', 'Đường đen', 'Trân châu', 'Kem cheese'],
    calories: 380,
    price: '30,000đ – 65,000đ',
    image: 'https://picsum.photos/600/900?random=82',
  },
  {
    id: 83,
    name: 'Cà Phê Sữa Đá',
    meal: 'drink',
    category: 'Đồ uống',
    style: 'Món nước',
    description: 'Cà phê sữa đá Việt Nam đặc trưng với cà phê phin đậm đà và sữa đặc ngọt ngào.',
    ingredients: ['Cà phê Robusta', 'Sữa đặc có đường', 'Đá'],
    calories: 180,
    price: '20,000đ – 40,000đ',
    image: 'https://picsum.photos/600/900?random=83',
  },
  {
    id: 84,
    name: 'Bạc Xỉu',
    meal: 'drink',
    category: 'Đồ uống',
    style: 'Món nước',
    description: 'Bạc xỉu Sài Gòn kiểu lai Hoa với nhiều sữa hơn cà phê ngọt nhẹ thơm béo dịu dàng.',
    ingredients: ['Cà phê', 'Sữa đặc', 'Sữa tươi', 'Đá'],
    calories: 210,
    price: '20,000đ – 40,000đ',
    image: 'https://picsum.photos/600/900?random=84',
  },
  {
    id: 85,
    name: 'Latte',
    meal: 'drink',
    category: 'Đồ uống',
    style: 'Món nước',
    description: 'Latte espresso với sữa tươi tạo bọt mịn mượt và art latte đẹp mắt tại quán cà phê.',
    ingredients: ['Espresso', 'Sữa tươi', 'Đá hoặc nóng'],
    calories: 150,
    price: '35,000đ – 65,000đ',
    image: 'https://picsum.photos/600/900?random=85',
  },
  {
    id: 86,
    name: 'Cappuccino',
    meal: 'drink',
    category: 'Đồ uống',
    style: 'Món nước',
    description: 'Cappuccino Ý cổ điển với espresso sữa tươi và lớp bọt foam mịn dày ấm áp.',
    ingredients: ['Espresso', 'Sữa tươi', 'Foam sữa', 'Bột cacao'],
    calories: 130,
    price: '35,000đ – 70,000đ',
    image: 'https://picsum.photos/600/900?random=86',
  },
  {
    id: 87,
    name: 'Matcha Latte',
    meal: 'drink',
    category: 'Đồ uống',
    style: 'Món nước',
    description: 'Matcha Latte với bột matcha Nhật Bản cao cấp xay cùng sữa tươi béo ngọt thanh tao.',
    ingredients: ['Matcha Nhật', 'Sữa tươi', 'Đường', 'Đá'],
    calories: 200,
    price: '40,000đ – 75,000đ',
    image: 'https://picsum.photos/600/900?random=87',
  },
  {
    id: 88,
    name: 'Sinh Tố Bơ',
    meal: 'drink',
    category: 'Đồ uống',
    style: 'Món nước',
    description: 'Sinh tố bơ béo ngậy xay mịn cùng sữa đặc và đá ngon ngất ngây thức uống bổ dưỡng.',
    ingredients: ['Bơ', 'Sữa đặc', 'Sữa tươi', 'Đá'],
    calories: 350,
    price: '30,000đ – 55,000đ',
    image: 'https://picsum.photos/600/900?random=88',
  },
  {
    id: 89,
    name: 'Sinh Tố Xoài',
    meal: 'drink',
    category: 'Đồ uống',
    style: 'Món nước',
    description: 'Sinh tố xoài vàng tươi ngọt thơm mát lạnh xay nhuyễn với đá và sữa béo ngon.',
    ingredients: ['Xoài cát', 'Sữa tươi', 'Đường', 'Đá'],
    calories: 260,
    price: '25,000đ – 50,000đ',
    image: 'https://picsum.photos/600/900?random=89',
  },
  {
    id: 90,
    name: 'Nước Cam',
    meal: 'drink',
    category: 'Đồ uống',
    style: 'Món nước',
    description: 'Nước cam vắt tươi nguyên chất ngọt thanh vitamin C dồi dào giải nhiệt hoàn hảo.',
    ingredients: ['Cam tươi', 'Đá', 'Đường (tuỳ chọn)'],
    calories: 110,
    price: '15,000đ – 35,000đ',
    image: 'https://picsum.photos/600/900?random=90',
  },
  {
    id: 91,
    name: 'Nước Chanh',
    meal: 'drink',
    category: 'Đồ uống',
    style: 'Món nước',
    description: 'Nước chanh tươi chua ngọt mát lạnh pha thêm muối hoặc gừng giải nhiệt tức thì.',
    ingredients: ['Chanh tươi', 'Đường', 'Muối', 'Đá'],
    calories: 90,
    price: '15,000đ – 30,000đ',
    image: 'https://picsum.photos/600/900?random=91',
  },
  {
    id: 92,
    name: 'Trà Đào',
    meal: 'drink',
    category: 'Đồ uống',
    style: 'Món nước',
    description: 'Trà đào thơm ngọt với đào xào đường và trà trái cây mát lạnh rất được giới trẻ yêu thích.',
    ingredients: ['Trà Peach Oolong', 'Đào', 'Đường', 'Đá'],
    calories: 180,
    price: '30,000đ – 55,000đ',
    image: 'https://picsum.photos/600/900?random=92',
  },
  {
    id: 93,
    name: 'Trà Tắc',
    meal: 'drink',
    category: 'Đồ uống',
    style: 'Món nước',
    description: 'Trà tắc chua ngọt thanh mát với trà pha tắc tươi và đá kéo dài ngày hè oi nóng.',
    ingredients: ['Trà đen', 'Tắc', 'Đường', 'Đá', 'Muối'],
    calories: 100,
    price: '15,000đ – 30,000đ',
    image: 'https://picsum.photos/600/900?random=93',
  },
  {
    id: 94,
    name: 'Trà Chanh',
    meal: 'drink',
    category: 'Đồ uống',
    style: 'Món nước',
    description: 'Trà chanh vỉa hè Hà Nội với trà thái đường đá và chanh vắt tươi ngon đậm chất Bắc.',
    ingredients: ['Trà đen', 'Chanh', 'Đường', 'Đá'],
    calories: 100,
    price: '10,000đ – 20,000đ',
    image: 'https://picsum.photos/600/900?random=94',
  },
  {
    id: 95,
    name: 'Soda',
    meal: 'drink',
    category: 'Đồ uống',
    style: 'Món nước',
    description: 'Soda kem xanh hoặc xí muội mát lạnh giải khát với bong bóng soda giòn tan rất sảng khoái.',
    ingredients: ['Soda', 'Kem', 'Xí muội', 'Siro'],
    calories: 130,
    price: '15,000đ – 30,000đ',
    image: 'https://picsum.photos/600/900?random=95',
  },
  {
    id: 96,
    name: 'Mojito',
    meal: 'drink',
    category: 'Đồ uống',
    style: 'Món nước',
    description: 'Mojito không cồn với bạc hà chanh và soda mát lạnh thơm mát và cực kỳ giải nhiệt.',
    ingredients: ['Bạc hà', 'Chanh', 'Đường', 'Soda', 'Đá'],
    calories: 110,
    price: '30,000đ – 55,000đ',
    image: 'https://picsum.photos/600/900?random=96',
  },
  {
    id: 97,
    name: 'Nước Mía',
    meal: 'drink',
    category: 'Đồ uống',
    style: 'Món nước',
    description: 'Nước mía vắt tươi ngọt thanh mát lạnh vỉa hè với quất và gừng thêm bổ dưỡng.',
    ingredients: ['Mía', 'Quất', 'Gừng', 'Đá'],
    calories: 150,
    price: '10,000đ – 25,000đ',
    image: 'https://picsum.photos/600/900?random=97',
  },
  {
    id: 98,
    name: 'Nước Dừa',
    meal: 'drink',
    category: 'Đồ uống',
    style: 'Món nước',
    description: 'Nước dừa tươi nguyên trái ngọt thanh giàu điện giải giải nhiệt và bổ dưỡng thiên nhiên.',
    ingredients: ['Dừa tươi'],
    calories: 120,
    price: '15,000đ – 30,000đ',
    image: 'https://picsum.photos/600/900?random=98',
  },
  {
    id: 99,
    name: 'Bún Bò Nam Bộ',
    meal: 'main',
    category: 'Ăn no',
    style: 'Món khô',
    description: 'Bún bò Nam Bộ khô trộn thịt bò xào sả ớt đậu phộng rang và rau sống tươi mát.',
    ingredients: ['Bún', 'Thịt bò', 'Sả', 'Đậu phộng', 'Giá đỗ', 'Rau thơm'],
    calories: 490,
    price: '40,000đ – 70,000đ',
    image: 'https://picsum.photos/600/900?random=99',
  },
  {
    id: 100,
    name: 'Bánh Xèo',
    meal: 'snack',
    category: 'Ăn nhẹ',
    style: 'Món khô',
    description: 'Bánh xèo giòn rụm vàng ươm nhân tôm thịt giá đỗ cuộn rau sống chấm nước mắm thơm.',
    ingredients: ['Bột gạo', 'Nước cốt dừa', 'Tôm', 'Thịt heo', 'Giá đỗ', 'Hành lá'],
    calories: 380,
    price: '30,000đ – 60,000đ',
    image: 'https://picsum.photos/600/900?random=100',
  },
];

/**
 * Async-compatible getter — swap with a real fetch() call when API is ready.
 * @returns {Promise<Array>}
 */
export async function getFoods() {
  return Promise.resolve(foods);
}
