export const REACTION_STATES = {
  WELCOME: 'welcome',
  SEARCH_COMPLETED: 'search-completed',
  REMAINING_GT_20: 'remaining-gt-20',
  REMAINING_20_TO_11: 'remaining-20-to-11',
  REMAINING_10_TO_6: 'remaining-10-to-6',
  REMAINING_5_TO_2: 'remaining-5-to-2',
  LAST_FOOD: 'last-food',
  EMPTY: 'empty',
  SELECTED: 'selected',
};

export const REACTION_DATA = {
  [REACTION_STATES.WELCOME]: {
    emojis: ['😊', '😄', '🤤', '🍜'],
    messages: [
      'Hôm nay mình ăn gì đây?',
      'Chào bạn! Để mình giúp chọn món nhé.',
      'Đói rồi đúng không? Bắt đầu thôi!',
      'Hy vọng hôm nay tìm được chân ái.',
      'Vuốt... à không, chọn món thôi nào!',
      'Mình đã sẵn sàng tìm món ngon.',
      'Bụng đói không nên suy nghĩ nhiều 😆',
      'Chỉ mất vài giây thôi.',
      'Hãy để mình quyết định cùng bạn.',
      'Chọn món chưa bao giờ vui thế này.',
    ],
  },
  [REACTION_STATES.SEARCH_COMPLETED]: {
    emojis: ['🤩', '😍', '😄', '🎉'],
    messages: [
      'Tìm thấy {count} món phù hợp.',
      'Có khá nhiều món ngon đây.',
      'Bắt đầu khám phá thôi!',
      'Hôm nay menu xịn đó.',
      'Đảm bảo sẽ có món hợp gu.',
      'Chỉ cần chọn một món thôi.',
      'Mình lọc giúp rồi đó.',
      'Toàn món ngon luôn.',
      'Khó mà chọn lắm đây.',
      'Đi thôi!',
    ],
  },
  [REACTION_STATES.REMAINING_GT_20]: {
    emojis: ['😄', '🙂'],
    messages: [
      'Còn nhiều món lắm.',
      'Không cần vội.',
      'Món ngon còn phía trước.',
      'Tiếp tục xem nhé.',
      'Còn nhiều bất ngờ.',
      'Đừng bỏ cuộc sớm.',
      'Chưa tới món chân ái đâu.',
      'Mình có linh cảm đó.',
      'Chắc chắn sẽ có món hợp.',
      'Tiếp nào!',
    ],
  },
  [REACTION_STATES.REMAINING_20_TO_11]: {
    emojis: ['😏', '🤔'],
    messages: [
      'Đã loại được kha khá rồi.',
      'Sắp tới món ngon rồi.',
      'Cố thêm chút nữa.',
      'Có vẻ gu bạn khá đặc biệt.',
      'Mình vẫn theo kịp 😄',
      'Tiếp tục nhé.',
      'Món hợp gu sắp xuất hiện.',
      'Đừng nản.',
      'Vẫn còn nhiều lựa chọn.',
      'Bình tĩnh nào.',
    ],
  },
  [REACTION_STATES.REMAINING_10_TO_6]: {
    emojis: ['😅', '😂'],
    messages: [
      'Chỉ còn vài món thôi.',
      'Khó tính ghê nha 😆',
      'Mình bắt đầu hồi hộp rồi.',
      'Đừng làm khó mình nữa.',
      'Chọn đại cũng ngon mà.',
      'Còn ít lắm rồi.',
      'Sắp hết danh sách.',
      'Quyết định khó ghê.',
      'Cố lên.',
      'Tin vào trực giác đi.',
    ],
  },
  [REACTION_STATES.REMAINING_5_TO_2]: {
    emojis: ['😤', '😨', '😭'],
    messages: [
      'Chỉ còn vài món cuối.',
      'Sắp hết thật rồi đó.',
      'Mình hết ý tưởng luôn 😭',
      'Khó chiều quá nha.',
      'Chắc món tiếp theo sẽ hợp.',
      'Tin mình thêm lần nữa.',
      'Đừng bỏ cuộc.',
      'Căng rồi 😅',
      'Mình bắt đầu lo rồi.',
      'Chọn lẹ không mình khóc đó.',
    ],
  },
  [REACTION_STATES.LAST_FOOD]: {
    emojis: ['🤣', '💀', '😭'],
    messages: [
      'Đây là món cuối cùng.',
      'Không còn món nào nữa 😭',
      'Hết thật rồi.',
      'Chắc phải tìm lại từ đầu thôi.',
      'Mình đã cố hết sức.',
      'Hy vọng bạn thích món này.',
      'Cơ hội cuối cùng.',
      'Tin mình lần cuối nha.',
      'Chọn đi mà 😆',
      'Đừng từ chối nữa.',
    ],
  },
  [REACTION_STATES.EMPTY]: {
    emojis: ['🤦', '😂', '😭'],
    messages: [
      'Bạn từ chối hết luôn rồi 😭',
      'Hay mình tìm lại nha?',
      'Không sao, thử lại thôi.',
      'Hôm nay khó chọn ghê.',
      'Chắc bụng chưa đói 😆',
      'Làm lại từ đầu nhé.',
      'Đừng lo, vẫn còn nhiều món khác.',
      'Mình sẽ tìm lại.',
      'Bắt đầu lại nào.',
      'Lần này chắc sẽ chọn được.',
    ],
  },
  [REACTION_STATES.SELECTED]: {
    emojis: ['🥳', '🎉', '😍', '🤤'],
    messages: [
      'Quyết định tuyệt vời!',
      'Chúc bạn ăn ngon miệng 😋',
      'Chốt đơn thành công!',
      'Món này đáng thử lắm.',
      'Mình cũng muốn ăn luôn.',
      'Ngon đó nha!',
      'Chúc bữa ăn thật vui.',
      'Đúng gu rồi đó.',
      'Quyết định sáng suốt.',
      'Ăn ngon và thật nhiều năng lượng nhé!',
    ],
  },
};